FROM ubuntu:latest

RUN apt-get update -y && apt-get install -y python3 python3-pip libpcre3 libpcre3-dev

COPY app /app/
WORKDIR /app
RUN pip3 install -r requirements.txt
RUN useradd -m wright

EXPOSE 5000

USER wright

ENV FLASK_APP=hello_flask.py
ENV FLASK_ENV=development
CMD ["uwsgi", "--http", ":5555", "--module", "hello_flask:app", "--master", "--processes", "4", "--threads", "2"]
